### ISSUE TITLE
Opening a minecraft:chest_minecart on 1.12.2 clears your inventory client side

### ISSUE THREAD

**Issue by Jaren8r** [MWHunter/Grim#365]
**Describe the bug**
Spawning a minecraft:chest_minecart and trying to open the chest inside of it clears your inventory instead of opening the chest. It logs this exception in console:
```
[07:59:25 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11 path $
        at com.google.gson.Gson.assertFullConsumption(Gson.java:863) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:853) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.github.retrooper.packetevents.adventure.serializer.gson.StyleSerializer.lambda$decoder$0(StyleSerializer.java:210) ~[?:?]
        at io.github.retrooper.packetevents.adventure.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializerImpl.deserializeShowEntity(NBTLegacyHoverEventSerializerImpl.java:75) ~[?:?]
        at io.github.retrooper.packetevents.adventure.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:197) ~[?:?]
        at io.github.retrooper.packetevents.adventure.serializer.gson.StyleSerializer.read(StyleSerializer.java:161) ~[?:?]
        at io.github.retrooper.packetevents.adventure.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[?:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.github.retrooper.packetevents.adventure.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[?:?]
        at io.github.retrooper.packetevents.adventure.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[?:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.github.retrooper.packetevents.adventure.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:84) ~[?:?]
        at io.github.retrooper.packetevents.adventure.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[?:?]
        at com.github.retrooper.packetevents.util.AdventureSerializer.parseComponent(AdventureSerializer.java:60) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readComponent(PacketWrapper.java:409) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerOpenWindow.read(WrapperPlayServerOpenWindow.java:85) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:152) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:100) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:90) ~[?:?]
        at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerOpenWindow.<init>(WrapperPlayServerOpenWindow.java:26) ~[?:?]
        at ac.grim.grimac.utils.latency.CompensatedInventory.onPacketSend(CompensatedInventory.java:187) ~[?:?]
        at ac.grim.grimac.manager.CheckManager.lambda$onPacketSend$3(CheckManager.java:157) ~[?:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[patched_1.12.2.jar:git-Paper-1620]
        at ac.grim.grimac.manager.CheckManager.onPacketSend(CheckManager.java:157) ~[?:?]
        at ac.grim.grimac.events.packets.CheckManagerListener.onPacketSend(CheckManagerListener.java:884) ~[?:?]
        at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:47) ~[?:?]
        at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:53) ~[?:?]
        at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:37) ~[?:?]
        at io.github.retrooper.packetevents.injector.latest.handlers.PacketEncoderLatest.encode(PacketEncoderLatest.java:59) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.google.gson.Gson.assertFullConsumption(Gson.java:859) ~[patched_1.12.2.jar:git-Paper-1620]
```

**To Reproduce**
1. Spawn a minecraft:chest_minecart
2. Try to open it
3. Observe

**Server Version**
git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Grim Version (Git commit or the version in the jar's name)**
abae7b2
**Relevant plugins**
GrimAC

**Comment by MWHunter** [comment]
Nevermind still an issue: https://gist.github.com/MWHunter/0a0e386179dc26d11522ab338cd78330

**Comment by MWHunter** [comment]
I changed packetevents code to no longer automatically serialize/deserialize the title for this packet, as a "temporary" fix.  Issue successfully hacked around.
