### ISSUE TITLE
Getting a error when starting up GRIMAC

### ISSUE THREAD

**Issue by ZeeceMC** [MWHunter/Grim#518]
**Describe the bug**
It keeps spamming: 
[00:11:53 ERROR]: Could not pass event PlayerJoinEvent to GrimAC v2.2.14
java.lang.IllegalStateException: PacketEvents failed to find a List indexed 0 by its type in the net.minecraft.network.PacketDecoder class!
    at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.reflection.ReflectionObject.getField(ReflectionObject.java:297) ~[grimac-2.2.14-all.jar:?]
    at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.reflection.ReflectionObject.read(ReflectionObject.java:159) ~[grimac-2.2.14-all.jar:?]
    at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.reflection.ReflectionObject.readList(ReflectionObject.java:284) ~[grimac-2.2.14-all.jar:?]
    at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.getDecoder(SpigotChannelInjector.java:291) ~[grimac-2.2.14-all.jar:?]
    at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.SpigotChannelInjector.updateUser(SpigotChannelInjector.java:244) ~[grimac-2.2.14-all.jar:?]
    at ac.grim.grimac.shaded.io.github.retrooper.packetevents.manager.player.PlayerManagerImpl.getUser(PlayerManagerImpl.java:117) ~[grimac-2.2.14-all.jar:?]
    at ac.grim.grimac.shaded.io.github.retrooper.packetevents.bukkit.InternalBukkitListener.onJoin(InternalBukkitListener.java:41) ~[grimac-2.2.14-all.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor150.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]

**To Reproduce**
/reload the server

**Server Version:**
1.18.2
**Grim Version (Git commit or the version in the jar's name)**
2.l2.14
**Relevant plugins**
AdvancedTeleport, AltDetector, BetterTeams, DiscordSRV, dynmap, Essentials, EssentialsSpawn, floodgate, Geyser-Spigot, LuckPerms, ProtocolLib, PvPManager, TerminatorPlus, ViaBackwards, ViaVersion, WolfyUtilities, WorldEdit

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/bfe9aba3a8b4605e5c8183a0d9e2cef1c2b698e8

You need to recompile grim for these changes
