### ISSUE TITLE
NBT 19 IOException and Dimensional attributes NPE

### ISSUE THREAD

**Issue by Labotomy** [MWHunter/Grim#543]
**Describe the bug**
IO Exception for unknown NBT 19 and dimensionalAttributes is null

**To Reproduce**
Install Plugin into a 1.19 spigot server, wait for players to trigger it, since it trips dimensionalAttributes likely when they use a portal

**Server Version:**
SpigotMC 1.19

**Grim Version (Git commit or the version in the jar's name)**
2.3.1 hotfix 2

**Relevant plugins**
none

[20:08:20] [Netty Epoll Server IO #0/WARN]: java.io.IOException: Unknown nbt type id 19
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.readTagType(NBTSerializer.java:89)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.deserializeTag(NBTSerializer.java:50)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.codec.NBTCodec.readNBT(NBTCodec.java:39)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readNBT(PacketWrapper.java:346)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.read(WrapperPlayServerRespawn.java:76)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:161)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:107)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:97)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.<init>(WrapperPlayServerRespawn.java:53)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:108)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:81)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:227)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:216)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:08:20] [Netty Epoll Server IO #0/WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getStringTagValueOrDefault(String, String)" because "dimensionAttributes" is null
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.read(WrapperPlayServerRespawn.java:77) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:161) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:107) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:97) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.<init>(WrapperPlayServerRespawn.java:53) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketSend(InternalPacketListener.java:108) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:81) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:227) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:216) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:08:20] [Netty Epoll Server IO #0/WARN]: java.io.IOException: Unknown nbt type id 19
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.readTagType(NBTSerializer.java:89)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.serializer.NBTSerializer.deserializeTag(NBTSerializer.java:50)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.codec.NBTCodec.readNBT(NBTCodec.java:39)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readNBT(PacketWrapper.java:346)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.read(WrapperPlayServerRespawn.java:76)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:161)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:107)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:97)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.<init>(WrapperPlayServerRespawn.java:53)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.events.packets.PacketPlayerRespawn.onPacketSend(PacketPlayerRespawn.java:70)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:81)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:227)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:216)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:08:20] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:08:20] [Netty Epoll Server IO #0/WARN]: PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.nbt.NBTCompound.getStringTagValueOrDefault(String, String)" because "dimensionAttributes" is null
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.read(WrapperPlayServerRespawn.java:77) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:161) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:107) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:97) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerRespawn.<init>(WrapperPlayServerRespawn.java:53) ~[?:?]
	at ac.grim.grimac.events.packets.PacketPlayerRespawn.onPacketSend(PacketPlayerRespawn.java:70) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[?:?]
	at ac.grim.grimac.shaded.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:41) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[?:?]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:81) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.76.Final.jar:4.1.76.Final]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:227) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:216) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar:4.1.76.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by MWHunter** [comment]
fixed by some packetevents commit, update to latest hotfix
