### ISSUE TITLE
Exception when joining

### ISSUE THREAD

**Issue by mfnalex** [MWHunter/Grim#557]
**Describe the bug**
Since updating to the latest Grim and Paper, I always get this when someone joins:
```
[09:36:22 INFO]: mfnalex joined the game
[09:36:22 INFO]: mfnalex[/5.147.150.7:1034] logged in with entity id 338 at ([world]-1.2467556041485217, 66.0, -1.2396233124543574)
[09:36:22 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
[09:36:22 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
        at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:81) ~[grimac-2.3.5-all.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[09:36:27 INFO]: mfnalex lost connection: Disconnected
[09:36:27 INFO]: mfnalex left the game
[09:36:29 INFO]: UUID of player mfnalex is 2214115f-fb07-49da-a954-8c757801be03
[09:36:29 INFO]: mfnalex joined the game
[09:36:29 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
[09:36:29 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
[09:36:29 INFO]: mfnalex[/5.147.150.7:1038] logged in with entity id 544 at ([world]-1.2467556041485217, 66.0, -1.2396233124543574)
[09:36:32 INFO]: mfnalex lost connection: Disconnected
[09:36:32 INFO]: mfnalex left the game
[09:36:48 INFO]: Checking version, please wait...
[09:36:48 INFO]: This server is running Paper version git-Paper-17 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4a48ed3)
```

Everything seems to be working fine though.

**To Reproduce**
Join

**Server Version:**
`Paper version git-Paper-17 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4a48ed3)`

**Grim Version (Git commit or the version in the jar's name)**
`grimac-2.3.5-all`

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/70405c4079d48ed328c8e22681f3db3ee36d3d1b
