### ISSUE TITLE
Some attributes are not lag compensated and are read from bukkit instead of packets

### ISSUE THREAD

**Issue by MWHunter** [MWHunter/Grim#88]
GENERIC_MOVEMENT_SPEED attribute
JUMP amplifier
LEVITATION amplifier
player flyspeed
player vehicle
player getFallDistance()

**Comment by MWHunter** [comment]
[14:33:55 WARN]: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[14:33:55 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.Chunk.a(Chunk.java:933)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.World.getEntities(World.java:1156)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.IEntityAccess.c(IEntityAccess.java:73)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.ICombinedAccess.c(SourceFile:22)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.ICollisionAccess.d(ICollisionAccess.java:65)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.ICollisionAccess.b(ICollisionAccess.java:58)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.ICollisionAccess.getCubes(ICollisionAccess.java:51)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.World.getCubes(World.java:963)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.Entity.b(Entity.java:675)
[14:33:55 WARN]:        at net.minecraft.server.v1_16_R3.Entity.e(Entity.java:671)
[14:33:55 WARN]:        at ac.grim.grimac.checks.movement.MovementVelocityCheck.livingEntityTravel(MovementVelocityCheck.java:210)
[14:33:55 WARN]:        at ac.grim.grimac.checks.movement.MovementVelocityCheck.playerEntityTravel(MovementVelocityCheck.java:134)
[14:33:55 WARN]:        at ac.grim.grimac.checks.movement.MovementVelocityCheck.livingEntityAIStep(MovementVelocityCheck.java:114)
[14:33:55 WARN]:        at ac.grim.grimac.checks.movement.MovementCheckRunner.check(MovementCheckRunner.java:85)
[14:33:55 WARN]:        at ac.grim.grimac.checks.movement.MovementCheckRunner.lambda$addQueuedPrediction$0(MovementCheckRunner.java:46)
[14:33:55 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[14:33:55 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[14:33:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[14:33:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[14:33:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by MWHunter** [comment]
and the world's worldborder :)

**Comment by MWHunter** [comment]
isFlyFalling

**Comment by MWHunter** [comment]
isClimbing

**Comment by MWHunter** [comment]
playFallDistance is fixed and is now safe

**Comment by MWHunter** [comment]
Fixed reading things async... kind of.  It still isn't thread safe but it's 99.99% thread safe which is "close enough" when the system is about to be replaced anyways.

Right now it need to be lag compensated.
